/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CodingGuru;

/**
 *
 * @author Yogeesh
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        AboutUs = new javax.swing.JButton();
        Heading = new javax.swing.JLabel();
        Tagline = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Header = new javax.swing.JLabel();
        FooterCredits = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Footer = new javax.swing.JLabel();
        Card1 = new javax.swing.JLabel();
        Card1Label = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card2Label = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        Card3Label = new javax.swing.JLabel();
        Card4 = new javax.swing.JLabel();
        Card4Label = new javax.swing.JLabel();
        Card5 = new javax.swing.JLabel();
        Card5Label = new javax.swing.JLabel();
        Card6 = new javax.swing.JLabel();
        Card6Label = new javax.swing.JLabel();
        Card7 = new javax.swing.JLabel();
        Card7Label = new javax.swing.JLabel();
        Card8 = new javax.swing.JLabel();
        Card8Label = new javax.swing.JLabel();
        Card9 = new javax.swing.JLabel();
        Card9Label = new javax.swing.JLabel();
        Card10 = new javax.swing.JLabel();
        Card10Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMinimumSize(new java.awt.Dimension(900, 500));
        MainPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutUs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/About Us.png"))); // NOI18N
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        MainPanel.add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, 30));

        Heading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("Coding Guru");
        Heading.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MainPanel.add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 60));

        Tagline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tagline.setForeground(new java.awt.Color(255, 255, 255));
        Tagline.setText("All Coding Courses in one Place.....");
        MainPanel.add(Tagline, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        Login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/User.png"))); // NOI18N
        Login.setText("User Page");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        MainPanel.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 140, 40));

        Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Banner Home Page.png"))); // NOI18N
        MainPanel.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        FooterCredits.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FooterCredits.setForeground(new java.awt.Color(255, 255, 255));
        FooterCredits.setText("Copyrigyt © Coding Guru");
        MainPanel.add(FooterCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 240, 50));

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        MainPanel.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 120, 30));

        Footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Footer Home Page.png"))); // NOI18N
        MainPanel.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 900, 50));

        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card1.png"))); // NOI18N
        Card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card1MouseClicked(evt);
            }
        });
        MainPanel.add(Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 100));

        Card1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card1Label.setText("Basics of Computer");
        Card1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card1LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, -1));

        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card2.png"))); // NOI18N
        Card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card2MouseClicked(evt);
            }
        });
        MainPanel.add(Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, 100));

        Card2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card2Label.setText("              Tally");
        Card2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card2LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 140, -1));

        Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card3.png"))); // NOI18N
        Card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card3MouseClicked(evt);
            }
        });
        MainPanel.add(Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 140, 100));

        Card3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card3Label.setText("              DTP");
        Card3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card3LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 140, -1));

        Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card4.png"))); // NOI18N
        Card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card4MouseClicked(evt);
            }
        });
        MainPanel.add(Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 140, 100));

        Card4Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card4Label.setText("     Complete Java");
        Card4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card4LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 140, -1));

        Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card12.png"))); // NOI18N
        Card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card5MouseClicked(evt);
            }
        });
        MainPanel.add(Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 140, 100));

        Card5Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card5Label.setText("        LAMP Stack");
        Card5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card5LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 140, -1));

        Card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card6.png"))); // NOI18N
        Card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card6MouseClicked(evt);
            }
        });
        MainPanel.add(Card6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 100));

        Card6Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card6Label.setText("              C++");
        Card6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card6LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card6Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, -1));

        Card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card7.png"))); // NOI18N
        Card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card7MouseClicked(evt);
            }
        });
        MainPanel.add(Card7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, 100));

        Card7Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card7Label.setText("            Python");
        Card7Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card7LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card7Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 140, -1));

        Card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card8.png"))); // NOI18N
        Card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card8MouseClicked(evt);
            }
        });
        MainPanel.add(Card8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 100));

        Card8Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card8Label.setText("             PHP");
        Card8Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card8LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card8Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 140, -1));

        Card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card10.png"))); // NOI18N
        Card9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card9MouseClicked(evt);
            }
        });
        MainPanel.add(Card9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 140, 100));

        Card9Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card9Label.setText("        MERN Stack");
        Card9Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card9LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card9Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 140, -1));

        Card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Card13.png"))); // NOI18N
        Card10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card10MouseClicked(evt);
            }
        });
        MainPanel.add(Card10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 140, 100));

        Card10Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Card10Label.setText("CSS3 + HTML5 + JS");
        Card10Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card10LabelMouseClicked(evt);
            }
        });
        MainPanel.add(Card10Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
            this.setVisible(false);
            this.dispose();
            AboutUs au = new AboutUs();
            au.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsActionPerformed

    private void Card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card1MouseClicked
            this.setVisible(false);
            this.dispose();
            Card1 obj = new Card1();
            obj.setVisible(true);
    }//GEN-LAST:event_Card1MouseClicked

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
            this.setVisible(false);
            this.dispose();
            UserPage up = new UserPage();
            up.PythonProgressBar.setValue(70);
            up.MERNProgress.setValue(25);
            up.setVisible(true);
            
    }//GEN-LAST:event_LoginActionPerformed

    private void Card1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card1LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card1 obj = new Card1();
            obj.setVisible(true);
    }//GEN-LAST:event_Card1LabelMouseClicked

    private void Card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card2MouseClicked
            this.setVisible(false);
            this.dispose();
            Card2 obj = new Card2();
            obj.setVisible(true);
    }//GEN-LAST:event_Card2MouseClicked

    private void Card2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card2LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card2 obj = new Card2();
            obj.setVisible(true);
    }//GEN-LAST:event_Card2LabelMouseClicked

    private void Card3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card3MouseClicked
            this.setVisible(false);
            this.dispose();
            Card3 obj = new Card3();
            obj.setVisible(true);
    }//GEN-LAST:event_Card3MouseClicked

    private void Card3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card3LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card3 obj = new Card3();
            obj.setVisible(true);
    }//GEN-LAST:event_Card3LabelMouseClicked

    private void Card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card4MouseClicked
            this.setVisible(false);
            this.dispose();
            Card4 obj = new Card4();
            obj.setVisible(true);        
    }//GEN-LAST:event_Card4MouseClicked

    private void Card4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card4LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card4 obj = new Card4();
            obj.setVisible(true);
    }//GEN-LAST:event_Card4LabelMouseClicked

    private void Card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card5MouseClicked
            this.setVisible(false);
            this.dispose();
            Card5 obj = new Card5();
            obj.setVisible(true);        
    }//GEN-LAST:event_Card5MouseClicked

    private void Card5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card5LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card5 obj = new Card5();
            obj.setVisible(true);        
    }//GEN-LAST:event_Card5LabelMouseClicked

    private void Card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card6MouseClicked
            this.setVisible(false);
            this.dispose();
            Card6 obj = new Card6();
            obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Card6MouseClicked

    private void Card6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card6LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card6 obj = new Card6();
            obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Card6LabelMouseClicked

    private void Card7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card7MouseClicked
            this.setVisible(false);
            this.dispose();
            Card7 obj = new Card7();
            obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Card7MouseClicked

    private void Card7LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card7LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card7 obj = new Card7();
            obj.setVisible(true);
    }//GEN-LAST:event_Card7LabelMouseClicked

    private void Card8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card8MouseClicked
            this.setVisible(false);
            this.dispose();
            Card8 obj = new Card8();
            obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Card8MouseClicked

    private void Card8LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card8LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card8 obj = new Card8();
            obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Card8LabelMouseClicked

    private void Card9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card9MouseClicked
            this.setVisible(false);
            this.dispose();
            Card9 obj = new Card9();
            obj.setVisible(true);
    }//GEN-LAST:event_Card9MouseClicked

    private void Card9LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card9LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card9 obj = new Card9();
            obj.setVisible(true);
    }//GEN-LAST:event_Card9LabelMouseClicked

    private void Card10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card10MouseClicked
            this.setVisible(false);
            this.dispose();
            Card10 obj = new Card10();
            obj.setVisible(true);
    }//GEN-LAST:event_Card10MouseClicked

    private void Card10LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card10LabelMouseClicked
            this.setVisible(false);
            this.dispose();
            Card10 obj = new Card10();
            obj.setVisible(true);
    }//GEN-LAST:event_Card10LabelMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
            this.setVisible(false);
            this.dispose();
            LoginPage obj = new LoginPage();
            obj.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card10;
    private javax.swing.JLabel Card10Label;
    private javax.swing.JLabel Card1Label;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card2Label;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Card3Label;
    private javax.swing.JLabel Card4;
    private javax.swing.JLabel Card4Label;
    private javax.swing.JLabel Card5;
    private javax.swing.JLabel Card5Label;
    private javax.swing.JLabel Card6;
    private javax.swing.JLabel Card6Label;
    private javax.swing.JLabel Card7;
    private javax.swing.JLabel Card7Label;
    private javax.swing.JLabel Card8;
    private javax.swing.JLabel Card8Label;
    private javax.swing.JLabel Card9;
    private javax.swing.JLabel Card9Label;
    private javax.swing.JLabel Footer;
    private javax.swing.JLabel FooterCredits;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton Login;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Tagline;
    // End of variables declaration//GEN-END:variables
}
