/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CodingGuru;

import javax.swing.JOptionPane;

/**
 *
 * @author Yogeesh
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Contact = new javax.swing.JLabel();
        RightCard1 = new javax.swing.JLabel();
        FooterCredits = new javax.swing.JLabel();
        TagLine = new javax.swing.JLabel();
        NameofInstitute = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        Footer = new javax.swing.JLabel();
        PageName = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UserNameInput = new javax.swing.JTextField();
        UserName = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Submit1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginPage");
        setName("MainFrame"); // NOI18N
        setResizable(false);

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("Any Problem Contact Admin");
        MainPanel.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, 30));

        RightCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Login Card2.png"))); // NOI18N
        MainPanel.add(RightCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 550, -1));

        FooterCredits.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FooterCredits.setForeground(new java.awt.Color(255, 255, 255));
        FooterCredits.setText("Copyrigyt © Coding Guru");
        MainPanel.add(FooterCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 240, 30));

        TagLine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TagLine.setForeground(new java.awt.Color(255, 255, 255));
        TagLine.setText("All Coding Courses in one Place.....");
        MainPanel.add(TagLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 280, -1));

        NameofInstitute.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        NameofInstitute.setForeground(new java.awt.Color(255, 255, 255));
        NameofInstitute.setText("Coding Guru");
        MainPanel.add(NameofInstitute, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 330, 70));

        Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Banner Home Page.png"))); // NOI18N
        MainPanel.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        Footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Footer Home Page.png"))); // NOI18N
        MainPanel.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 900, 50));

        PageName.setFont(new java.awt.Font("Gabriola", 3, 36)); // NOI18N
        PageName.setText("User Login");
        MainPanel.add(PageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, 40));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/Password.png"))); // NOI18N
        Password.setText("Password :");
        MainPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 30));

        UserNameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameInputActionPerformed(evt);
            }
        });
        MainPanel.add(UserNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, 30));

        UserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/User1.png"))); // NOI18N
        UserName.setText("User Name :");
        MainPanel.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 30));

        PasswordInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordInputActionPerformed(evt);
            }
        });
        MainPanel.add(PasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, 30));

        Register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/Signup.png"))); // NOI18N
        Register.setText("Registration");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        MainPanel.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, -1));

        Submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/Submit.png"))); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        MainPanel.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        Submit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/Admin.png"))); // NOI18N
        Submit1.setText("Admin Login");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });
        MainPanel.add(Submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Icons/Reset.png"))); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        MainPanel.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameInputActionPerformed

    private void PasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordInputActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
            this.setVisible(false);
            this.dispose();
            Registration lp = new Registration();
            lp.setVisible(true);
    }//GEN-LAST:event_RegisterActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
            String str1 = UserNameInput.getText();
            String str2 = new String(PasswordInput.getPassword());
            String uname = "Yogeesh",upass = "12345";
           if(!"".equals(str1))
            {
                if(!"".equals(str2))
                {
                    if(str1.equals(uname))
                    {
                        if(str2.equals(upass))
                        {
                                    this.setVisible(false);
                                    this.dispose();
                                    HomePage hp = new HomePage();
                                    hp.setVisible(true);
                                    
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Invalid Password");  
                        }
                                            
                    }
                    else if(!str2.equals(upass))
                    {
                        JOptionPane.showMessageDialog(null, "Invalid User Name and Password");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Invalid User Name");
                    }
                }
                else
                    JOptionPane.showMessageDialog(null, "Please Enter Password");
            }
            else if("".equals(str2))
            {
                JOptionPane.showMessageDialog(null, "Please Enter User Name and Password");
            }
            else
                JOptionPane.showMessageDialog(null, "Please Enter User Name");
            
    }//GEN-LAST:event_SubmitActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed
                        this.setVisible(false);
                        this.dispose();
                        AdminLogin adl = new AdminLogin();
                        adl.setVisible(true);
                  
    }//GEN-LAST:event_Submit1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
             UserNameInput.setText("");
             PasswordInput.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Footer;
    private javax.swing.JLabel FooterCredits;
    private javax.swing.JLabel Header;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NameofInstitute;
    private javax.swing.JLabel PageName;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton Register;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel RightCard1;
    private javax.swing.JButton Submit;
    private javax.swing.JButton Submit1;
    private javax.swing.JLabel TagLine;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserNameInput;
    // End of variables declaration//GEN-END:variables
}
