/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CodingGuru;

import javax.swing.JOptionPane;

/**
 *
 * @author Yogeesh
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LodingBar = new javax.swing.JProgressBar();
        BackGroundPanel = new javax.swing.JPanel();
        Tagline = new javax.swing.JLabel();
        InstituteName = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BackGroundPanel.setBackground(new java.awt.Color(51, 204, 255));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tagline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tagline.setForeground(new java.awt.Color(255, 255, 255));
        Tagline.setText("All Coding Courses in one Place.....");
        BackGroundPanel.add(Tagline, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 260, 20));

        InstituteName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        InstituteName.setForeground(new java.awt.Color(255, 255, 255));
        InstituteName.setText("Coding Guru");
        BackGroundPanel.add(InstituteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 300, 100));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setText("Starting.....");
        BackGroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/Logo.png"))); // NOI18N
        BackGroundPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 370, 320));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText(" 99 %");
        BackGroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 40, -1));

        LoadingBar.setBackground(new java.awt.Color(255, 255, 255));
        LoadingBar.setForeground(new java.awt.Color(255, 51, 0));
        LoadingBar.setAlignmentX(0.0F);
        LoadingBar.setAlignmentY(0.0F);
        LoadingBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        BackGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 900, 10));

        BackgroundImage.setForeground(new java.awt.Color(255, 51, 0));
        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodingGuru/Assets/LodingScreenBackground.png"))); // NOI18N
        BackGroundPanel.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        final SplashScreen sp = new SplashScreen();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sp.setVisible(true);
            }
        });
        
        //final SplashScreen sp = new SplashScreen();

        
        
        try{
            for(int i=0; i<=100; i++) {
                 Thread.sleep(100);
                   sp.LoadingBar.setValue(i);
                   if(i<10){
                        sp.LoadingValue.setText("    "+i + "%");
                   }
                   else if(i<100){
                        sp.LoadingValue.setText("  "+i + "%");
                   }
                   else{
                       sp.LoadingValue.setText(i + "%");
                   }
                         
                 if(i==10){
                    sp.LoadingLabel.setText("Finding Modules...");
                 }
                 
                 if(i==20){
                    sp.LoadingLabel.setText("Starting Modules...");
                 }
                 
                 if(i==30){
                    sp.LoadingLabel.setText("Loading Modules...");
                 }
   
                 if(i==80){
                    sp.LoadingLabel.setText("Done Loading Modules...");
                 }
                 
                 if(i==90){
                    sp.LoadingLabel.setText("Launching Application...");
                 }
                 if(i==100){
                    sp.setVisible(false);
                    LoginPage  lp = new LoginPage();
                    lp.setVisible(true);
                    sp.dispose();
                    
                 }
                 
            
            } 
   
        }
    
            catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
               }
        

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel InstituteName;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JProgressBar LodingBar;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Tagline;
    // End of variables declaration//GEN-END:variables
}
